In [65]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('OperatiiData').getOrCreate()
df = spark.read.csv('datebancare.csv', inferSchema=True, header=True)

In [66]:
df.take(2)

[Row(age=59, job='admin.', marital='married', education='secondary', default='no', balance=2343, housing='yes', loan='no', contact='unknown', day=5, month='may', duration=1042, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=56, job='admin.', marital='married', education='secondary', default='no', balance=45, housing='no', loan='no', contact='unknown', day=5, month='may', duration=1467, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes')]

In [67]:
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- job: string (nullable = true)
 |-- marital: string (nullable = true)
 |-- education: string (nullable = true)
 |-- default: string (nullable = true)
 |-- balance: integer (nullable = true)
 |-- housing: string (nullable = true)
 |-- loan: string (nullable = true)
 |-- contact: string (nullable = true)
 |-- day: integer (nullable = true)
 |-- month: string (nullable = true)
 |-- duration: integer (nullable = true)
 |-- campaign: integer (nullable = true)
 |-- pdays: integer (nullable = true)
 |-- previous: integer (nullable = true)
 |-- poutcome: string (nullable = true)
 |-- deposit: string (nullable = true)

In [68]:
df.show(3)

+---+----------+-------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
|age|       job|marital|education|default|balance|housing|loan|contact|day|month|duration|campaign|pdays|previous|poutcome|deposit|
+---+----------+-------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
| 59|    admin.|married|secondary|     no|   2343|    yes|  no|unknown|  5|  may|    1042|       1|   -1|       0| unknown|    yes|
| 56|    admin.|married|secondary|     no|     45|     no|  no|unknown|  5|  may|    1467|       1|   -1|       0| unknown|    yes|
| 41|technician|married|secondary|     no|   1270|    yes|  no|unknown|  5|  may|    1389|       1|   -1|       0| unknown|    yes|
+---+----------+-------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
only showing top 3 rows

In [69]:
df.select(['age', 'job']).show()

+---+-----------+
|age|        job|
+---+-----------+
| 59|     admin.|
| 56|     admin.|
| 41| technician|
| 55|   services|
| 54|     admin.|
| 42| management|
| 56| management|
| 60|    retired|
| 37| technician|
| 28|   services|
| 38|     admin.|
| 30|blue-collar|
| 29| management|
| 46|blue-collar|
| 31| technician|
| 35| management|
| 32|blue-collar|
| 49|   services|
| 41|     admin.|
| 49|     admin.|
+---+-----------+
only showing top 20 rows

In [70]:
df.filter(df['age'] == 41).show()

+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
|age|         job| marital|education|default|balance|housing|loan|contact|day|month|duration|campaign|pdays|previous|poutcome|deposit|
+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
| 41|  technician| married|secondary|     no|   1270|    yes|  no|unknown|  5|  may|    1389|       1|   -1|       0| unknown|    yes|
| 41|      admin.| married|secondary|     no|     55|    yes|  no|unknown|  8|  may|    1120|       2|   -1|       0| unknown|    yes|
| 41| blue-collar|  single|  primary|     no|   1618|    yes|  no|unknown| 14|  may|    1553|       1|   -1|       0| unknown|    yes|
| 41| blue-collar| married|secondary|     no|   2823|    yes|  no|unknown| 14|  may|     858|       1|   -1|       0| unknown|    yes|
| 41| blue-collar|divorced|secondary|     no|   5291|    yes|  no|unknown| 14|  may|    1423|       3|   -1|       0| unknown|    yes|
| 41| blue-collar| married|secondary|     no|   1384|    yes|  no|unknown| 15|  may|    1162|       4|   -1|       0| unknown|    yes|
| 41|      admin.| married|  primary|     no|   -306|    yes|  no|unknown| 15|  may|     500|       1|   -1|       0| unknown|    yes|
| 41|     retired|divorced|  primary|     no|   -233|    yes|  no|unknown| 15|  may|    1156|       2|   -1|       0| unknown|    yes|
| 41| blue-collar| married|  primary|     no|   2453|    yes|  no|unknown| 15|  may|    1052|       1|   -1|       0| unknown|    yes|
| 41|      admin.|  single|secondary|     no|   1020|    yes|  no|unknown| 19|  may|     882|       1|   -1|       0| unknown|    yes|
| 41|  technician| married|secondary|     no|    501|    yes|  no|unknown| 19|  may|     579|       5|   -1|       0| unknown|    yes|
| 41| blue-collar| married|  primary|     no|   1250|    yes|  no|unknown| 20|  may|    1392|       2|   -1|       0| unknown|    yes|
| 41| blue-collar| married|  primary|     no|    143|    yes| yes|unknown|  2|  jun|     659|       2|   -1|       0| unknown|    yes|
| 41|   housemaid| married|secondary|     no|    879|     no|  no|unknown|  5|  jun|    1053|       2|   -1|       0| unknown|    yes|
| 41|      admin.|  single|secondary|     no|    812|     no| yes|unknown| 11|  jun|     583|       4|   -1|       0| unknown|    yes|
| 41|  management|  single| tertiary|     no|  11008|     no|  no|unknown| 18|  jun|    1540|       1|   -1|       0| unknown|    yes|
| 41|entrepreneur| married|secondary|     no|    707|     no|  no|unknown| 18|  jun|     707|       1|   -1|       0| unknown|    yes|
| 41| blue-collar| married|  primary|     no|    219|     no| yes|unknown| 18|  jun|    1574|       3|   -1|       0| unknown|    yes|
| 41| blue-collar|divorced|secondary|     no|   3622|     no|  no|unknown| 19|  jun|    1135|       4|   -1|       0| unknown|    yes|
| 41| blue-collar| married|  primary|     no|    246|     no|  no|unknown| 19|  jun|     683|       3|   -1|       0| unknown|    yes|
+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
only showing top 20 rows

In [71]:
df.filter(df['age'] ==41).collect()

[Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=1270, housing='yes', loan='no', contact='unknown', day=5, month='may', duration=1389, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='married', education='secondary', default='no', balance=55, housing='yes', loan='no', contact='unknown', day=8, month='may', duration=1120, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='primary', default='no', balance=1618, housing='yes', loan='no', contact='unknown', day=14, month='may', duration=1553, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=2823, housing='yes', loan='no', contact='unknown', day=14, month='may', duration=858, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='secondary', default='no', balance=5291, housing='yes', loan='no', contact='unknown', day=14, month='may', duration=1423, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=1384, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=1162, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='married', education='primary', default='no', balance=-306, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=500, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='retired', marital='divorced', education='primary', default='no', balance=-233, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=1156, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=2453, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=1052, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='single', education='secondary', default='no', balance=1020, housing='yes', loan='no', contact='unknown', day=19, month='may', duration=882, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=501, housing='yes', loan='no', contact='unknown', day=19, month='may', duration=579, campaign=5, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=1250, housing='yes', loan='no', contact='unknown', day=20, month='may', duration=1392, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=143, housing='yes', loan='yes', contact='unknown', day=2, month='jun', duration=659, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='housemaid', marital='married', education='secondary', default='no', balance=879, housing='no', loan='no', contact='unknown', day=5, month='jun', duration=1053, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='single', education='secondary', default='no', balance=812, housing='no', loan='yes', contact='unknown', day=11, month='jun', duration=583, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='tertiary', default='no', balance=11008, housing='no', loan='no', contact='unknown', day=18, month='jun', duration=1540, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='married', education='secondary', default='no', balance=707, housing='no', loan='no', contact='unknown', day=18, month='jun', duration=707, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=219, housing='no', loan='yes', contact='unknown', day=18, month='jun', duration=1574, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='secondary', default='no', balance=3622, housing='no', loan='no', contact='unknown', day=19, month='jun', duration=1135, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=246, housing='no', loan='no', contact='unknown', day=19, month='jun', duration=683, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='secondary', default='no', balance=75, housing='yes', loan='no', contact='unknown', day=1, month='jul', duration=479, campaign=9, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='secondary', default='yes', balance=1085, housing='yes', loan='yes', contact='cellular', day=7, month='jul', duration=599, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='divorced', education='tertiary', default='no', balance=1583, housing='yes', loan='no', contact='cellular', day=9, month='jul', duration=662, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='primary', default='no', balance=138, housing='yes', loan='no', contact='cellular', day=18, month='jul', duration=640, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='tertiary', default='no', balance=1253, housing='no', loan='no', contact='cellular', day=21, month='jul', duration=1134, campaign=5, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='tertiary', default='no', balance=145, housing='no', loan='no', contact='cellular', day=22, month='jul', duration=1833, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='divorced', education='unknown', default='no', balance=465, housing='yes', loan='no', contact='cellular', day=22, month='jul', duration=1508, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='single', education='secondary', default='no', balance=663, housing='no', loan='no', contact='cellular', day=24, month='jul', duration=1204, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='yes', balance=720, housing='no', loan='yes', contact='cellular', day=24, month='jul', duration=651, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='married', education='unknown', default='no', balance=1538, housing='no', loan='no', contact='cellular', day=29, month='jul', duration=710, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=-190, housing='no', loan='yes', contact='cellular', day=29, month='jul', duration=808, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='married', education='unknown', default='yes', balance=-1, housing='no', loan='yes', contact='cellular', day=30, month='jul', duration=1171, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='primary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=30, month='jul', duration=509, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='tertiary', default='no', balance=515, housing='no', loan='no', contact='cellular', day=5, month='aug', duration=837, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='married', education='tertiary', default='no', balance=231, housing='no', loan='no', contact='cellular', day=7, month='aug', duration=352, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='secondary', default='no', balance=456, housing='yes', loan='no', contact='cellular', day=11, month='aug', duration=734, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=11, month='aug', duration=1242, campaign=5, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='tertiary', default='no', balance=231, housing='no', loan='no', contact='cellular', day=26, month='aug', duration=428, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=0, housing='yes', loan='no', contact='cellular', day=18, month='nov', duration=897, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='secondary', default='yes', balance=-386, housing='no', loan='yes', contact='cellular', day=20, month='nov', duration=477, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='tertiary', default='no', balance=1982, housing='no', loan='no', contact='cellular', day=21, month='nov', duration=558, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='single', education='secondary', default='no', balance=92, housing='no', loan='no', contact='cellular', day=21, month='nov', duration=372, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='married', education='primary', default='no', balance=39, housing='yes', loan='no', contact='cellular', day=21, month='nov', duration=549, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='secondary', default='no', balance=3234, housing='yes', loan='no', contact='cellular', day=30, month='jan', duration=2770, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='divorced', education='secondary', default='no', balance=840, housing='yes', loan='no', contact='cellular', day=2, month='feb', duration=938, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=201, housing='yes', loan='no', contact='cellular', day=3, month='feb', duration=157, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='single', education='tertiary', default='no', balance=-94, housing='yes', loan='no', contact='cellular', day=4, month='feb', duration=1164, campaign=1, pdays=203, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=1066, housing='no', loan='no', contact='cellular', day=11, month='feb', duration=109, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='divorced', education='secondary', default='no', balance=4047, housing='yes', loan='no', contact='cellular', day=18, month='feb', duration=343, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='secondary', default='no', balance=280, housing='yes', loan='no', contact='cellular', day=27, month='feb', duration=87, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='divorced', education='tertiary', default='no', balance=25, housing='yes', loan='yes', contact='cellular', day=26, month='mar', duration=117, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=1468, housing='yes', loan='no', contact='cellular', day=31, month='mar', duration=237, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='married', education='secondary', default='no', balance=3123, housing='yes', loan='no', contact='cellular', day=3, month='apr', duration=1203, campaign=2, pdays=135, previous=2, poutcome='failure', deposit='yes'),
 Row(age=41, job='services', marital='married', education='secondary', default='no', balance=803, housing='yes', loan='no', contact='cellular', day=9, month='apr', duration=592, campaign=4, pdays=316, previous=3, poutcome='failure', deposit='yes'),
 Row(age=41, job='housemaid', marital='married', education='primary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=14, month='apr', duration=168, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='married', education='secondary', default='no', balance=323, housing='yes', loan='no', contact='cellular', day=17, month='apr', duration=949, campaign=2, pdays=254, previous=6, poutcome='other', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=4004, housing='no', loan='no', contact='cellular', day=17, month='apr', duration=314, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='primary', default='no', balance=285, housing='yes', loan='no', contact='cellular', day=20, month='apr', duration=1272, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='unknown', marital='single', education='unknown', default='no', balance=942, housing='no', loan='no', contact='cellular', day=22, month='apr', duration=219, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=5060, housing='no', loan='no', contact='cellular', day=4, month='may', duration=963, campaign=1, pdays=83, previous=3, poutcome='success', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=326, housing='yes', loan='no', contact='cellular', day=5, month='may', duration=788, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='single', education='secondary', default='no', balance=-109, housing='yes', loan='yes', contact='cellular', day=11, month='may', duration=1038, campaign=1, pdays=370, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=1236, housing='yes', loan='no', contact='cellular', day=11, month='may', duration=911, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=580, housing='yes', loan='no', contact='cellular', day=14, month='may', duration=874, campaign=1, pdays=363, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='self-employed', marital='single', education='tertiary', default='no', balance=1081, housing='no', loan='no', contact='cellular', day=27, month='may', duration=229, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='married', education='secondary', default='no', balance=0, housing='yes', loan='yes', contact='cellular', day=4, month='jun', duration=352, campaign=2, pdays=122, previous=2, poutcome='failure', deposit='yes'),
 Row(age=41, job='unemployed', marital='single', education='primary', default='no', balance=216, housing='no', loan='no', contact='cellular', day=5, month='jun', duration=577, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=203, housing='no', loan='no', contact='cellular', day=2, month='jul', duration=342, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='married', education='primary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=3, month='jul', duration=438, campaign=2, pdays=389, previous=1, poutcome='other', deposit='yes'),
 Row(age=41, job='admin.', marital='married', education='tertiary', default='no', balance=1536, housing='no', loan='no', contact='cellular', day=7, month='aug', duration=273, campaign=1, pdays=95, previous=2, poutcome='failure', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=27696, housing='no', loan='no', contact='cellular', day=12, month='aug', duration=147, campaign=2, pdays=104, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='admin.', marital='divorced', education='secondary', default='no', balance=6046, housing='yes', loan='yes', contact='telephone', day=14, month='sep', duration=185, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='tertiary', default='no', balance=431, housing='no', loan='no', contact='cellular', day=22, month='oct', duration=133, campaign=1, pdays=107, previous=2, poutcome='success', deposit='yes'),
 Row(age=41, job='unknown', marital='single', education='unknown', default='no', balance=942, housing='no', loan='no', contact='cellular', day=27, month='oct', duration=143, campaign=1, pdays=188, previous=1, poutcome='success', deposit='yes'),
 Row(age=41, job='services', marital='married', education='tertiary', default='no', balance=881, housing='no', loan='no', contact='cellular', day=30, month='oct', duration=257, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='unknown', default='no', balance=5372, housing='yes', loan='no', contact='cellular', day=13, month='jan', duration=248, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='tertiary', default='no', balance=1646, housing='yes', loan='no', contact='cellular', day=4, month='feb', duration=261, campaign=1, pdays=184, previous=6, poutcome='success', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=27696, housing='no', loan='no', contact='cellular', day=12, month='feb', duration=138, campaign=2, pdays=184, previous=3, poutcome='success', deposit='yes'),
 Row(age=41, job='management', marital='divorced', education='tertiary', default='no', balance=5037, housing='no', loan='no', contact='cellular', day=23, month='apr', duration=252, campaign=9, pdays=185, previous=5, poutcome='other', deposit='yes'),
 Row(age=41, job='unemployed', marital='married', education='tertiary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=29, month='apr', duration=882, campaign=1, pdays=181, previous=3, poutcome='success', deposit='yes'),

In [72]:
result = df.filter(df['age'] ==41).collect()

In [73]:
result

[Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=1270, housing='yes', loan='no', contact='unknown', day=5, month='may', duration=1389, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='married', education='secondary', default='no', balance=55, housing='yes', loan='no', contact='unknown', day=8, month='may', duration=1120, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='primary', default='no', balance=1618, housing='yes', loan='no', contact='unknown', day=14, month='may', duration=1553, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=2823, housing='yes', loan='no', contact='unknown', day=14, month='may', duration=858, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='secondary', default='no', balance=5291, housing='yes', loan='no', contact='unknown', day=14, month='may', duration=1423, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=1384, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=1162, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='married', education='primary', default='no', balance=-306, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=500, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='retired', marital='divorced', education='primary', default='no', balance=-233, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=1156, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=2453, housing='yes', loan='no', contact='unknown', day=15, month='may', duration=1052, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='single', education='secondary', default='no', balance=1020, housing='yes', loan='no', contact='unknown', day=19, month='may', duration=882, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=501, housing='yes', loan='no', contact='unknown', day=19, month='may', duration=579, campaign=5, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=1250, housing='yes', loan='no', contact='unknown', day=20, month='may', duration=1392, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=143, housing='yes', loan='yes', contact='unknown', day=2, month='jun', duration=659, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='housemaid', marital='married', education='secondary', default='no', balance=879, housing='no', loan='no', contact='unknown', day=5, month='jun', duration=1053, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='single', education='secondary', default='no', balance=812, housing='no', loan='yes', contact='unknown', day=11, month='jun', duration=583, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='tertiary', default='no', balance=11008, housing='no', loan='no', contact='unknown', day=18, month='jun', duration=1540, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='married', education='secondary', default='no', balance=707, housing='no', loan='no', contact='unknown', day=18, month='jun', duration=707, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=219, housing='no', loan='yes', contact='unknown', day=18, month='jun', duration=1574, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='secondary', default='no', balance=3622, housing='no', loan='no', contact='unknown', day=19, month='jun', duration=1135, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=246, housing='no', loan='no', contact='unknown', day=19, month='jun', duration=683, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='secondary', default='no', balance=75, housing='yes', loan='no', contact='unknown', day=1, month='jul', duration=479, campaign=9, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='secondary', default='yes', balance=1085, housing='yes', loan='yes', contact='cellular', day=7, month='jul', duration=599, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='divorced', education='tertiary', default='no', balance=1583, housing='yes', loan='no', contact='cellular', day=9, month='jul', duration=662, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='primary', default='no', balance=138, housing='yes', loan='no', contact='cellular', day=18, month='jul', duration=640, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='tertiary', default='no', balance=1253, housing='no', loan='no', contact='cellular', day=21, month='jul', duration=1134, campaign=5, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='tertiary', default='no', balance=145, housing='no', loan='no', contact='cellular', day=22, month='jul', duration=1833, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='divorced', education='unknown', default='no', balance=465, housing='yes', loan='no', contact='cellular', day=22, month='jul', duration=1508, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='single', education='secondary', default='no', balance=663, housing='no', loan='no', contact='cellular', day=24, month='jul', duration=1204, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='yes', balance=720, housing='no', loan='yes', contact='cellular', day=24, month='jul', duration=651, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='married', education='unknown', default='no', balance=1538, housing='no', loan='no', contact='cellular', day=29, month='jul', duration=710, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=-190, housing='no', loan='yes', contact='cellular', day=29, month='jul', duration=808, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='married', education='unknown', default='yes', balance=-1, housing='no', loan='yes', contact='cellular', day=30, month='jul', duration=1171, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='primary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=30, month='jul', duration=509, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='tertiary', default='no', balance=515, housing='no', loan='no', contact='cellular', day=5, month='aug', duration=837, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='married', education='tertiary', default='no', balance=231, housing='no', loan='no', contact='cellular', day=7, month='aug', duration=352, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='secondary', default='no', balance=456, housing='yes', loan='no', contact='cellular', day=11, month='aug', duration=734, campaign=4, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=11, month='aug', duration=1242, campaign=5, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='tertiary', default='no', balance=231, housing='no', loan='no', contact='cellular', day=26, month='aug', duration=428, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=0, housing='yes', loan='no', contact='cellular', day=18, month='nov', duration=897, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='single', education='secondary', default='yes', balance=-386, housing='no', loan='yes', contact='cellular', day=20, month='nov', duration=477, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='tertiary', default='no', balance=1982, housing='no', loan='no', contact='cellular', day=21, month='nov', duration=558, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='single', education='secondary', default='no', balance=92, housing='no', loan='no', contact='cellular', day=21, month='nov', duration=372, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='married', education='primary', default='no', balance=39, housing='yes', loan='no', contact='cellular', day=21, month='nov', duration=549, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='single', education='secondary', default='no', balance=3234, housing='yes', loan='no', contact='cellular', day=30, month='jan', duration=2770, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='divorced', education='secondary', default='no', balance=840, housing='yes', loan='no', contact='cellular', day=2, month='feb', duration=938, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='primary', default='no', balance=201, housing='yes', loan='no', contact='cellular', day=3, month='feb', duration=157, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='single', education='tertiary', default='no', balance=-94, housing='yes', loan='no', contact='cellular', day=4, month='feb', duration=1164, campaign=1, pdays=203, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=1066, housing='no', loan='no', contact='cellular', day=11, month='feb', duration=109, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='divorced', education='secondary', default='no', balance=4047, housing='yes', loan='no', contact='cellular', day=18, month='feb', duration=343, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='secondary', default='no', balance=280, housing='yes', loan='no', contact='cellular', day=27, month='feb', duration=87, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='divorced', education='tertiary', default='no', balance=25, housing='yes', loan='yes', contact='cellular', day=26, month='mar', duration=117, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=1468, housing='yes', loan='no', contact='cellular', day=31, month='mar', duration=237, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='married', education='secondary', default='no', balance=3123, housing='yes', loan='no', contact='cellular', day=3, month='apr', duration=1203, campaign=2, pdays=135, previous=2, poutcome='failure', deposit='yes'),
 Row(age=41, job='services', marital='married', education='secondary', default='no', balance=803, housing='yes', loan='no', contact='cellular', day=9, month='apr', duration=592, campaign=4, pdays=316, previous=3, poutcome='failure', deposit='yes'),
 Row(age=41, job='housemaid', marital='married', education='primary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=14, month='apr', duration=168, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='self-employed', marital='married', education='secondary', default='no', balance=323, housing='yes', loan='no', contact='cellular', day=17, month='apr', duration=949, campaign=2, pdays=254, previous=6, poutcome='other', deposit='yes'),
 Row(age=41, job='technician', marital='married', education='secondary', default='no', balance=4004, housing='no', loan='no', contact='cellular', day=17, month='apr', duration=314, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='divorced', education='primary', default='no', balance=285, housing='yes', loan='no', contact='cellular', day=20, month='apr', duration=1272, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='unknown', marital='single', education='unknown', default='no', balance=942, housing='no', loan='no', contact='cellular', day=22, month='apr', duration=219, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=5060, housing='no', loan='no', contact='cellular', day=4, month='may', duration=963, campaign=1, pdays=83, previous=3, poutcome='success', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=326, housing='yes', loan='no', contact='cellular', day=5, month='may', duration=788, campaign=1, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='admin.', marital='single', education='secondary', default='no', balance=-109, housing='yes', loan='yes', contact='cellular', day=11, month='may', duration=1038, campaign=1, pdays=370, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=1236, housing='yes', loan='no', contact='cellular', day=11, month='may', duration=911, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=580, housing='yes', loan='no', contact='cellular', day=14, month='may', duration=874, campaign=1, pdays=363, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='self-employed', marital='single', education='tertiary', default='no', balance=1081, housing='no', loan='no', contact='cellular', day=27, month='may', duration=229, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='services', marital='married', education='secondary', default='no', balance=0, housing='yes', loan='yes', contact='cellular', day=4, month='jun', duration=352, campaign=2, pdays=122, previous=2, poutcome='failure', deposit='yes'),
 Row(age=41, job='unemployed', marital='single', education='primary', default='no', balance=216, housing='no', loan='no', contact='cellular', day=5, month='jun', duration=577, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='blue-collar', marital='married', education='secondary', default='no', balance=203, housing='no', loan='no', contact='cellular', day=2, month='jul', duration=342, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='entrepreneur', marital='married', education='primary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=3, month='jul', duration=438, campaign=2, pdays=389, previous=1, poutcome='other', deposit='yes'),
 Row(age=41, job='admin.', marital='married', education='tertiary', default='no', balance=1536, housing='no', loan='no', contact='cellular', day=7, month='aug', duration=273, campaign=1, pdays=95, previous=2, poutcome='failure', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=27696, housing='no', loan='no', contact='cellular', day=12, month='aug', duration=147, campaign=2, pdays=104, previous=1, poutcome='failure', deposit='yes'),
 Row(age=41, job='admin.', marital='divorced', education='secondary', default='no', balance=6046, housing='yes', loan='yes', contact='telephone', day=14, month='sep', duration=185, campaign=2, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='tertiary', default='no', balance=431, housing='no', loan='no', contact='cellular', day=22, month='oct', duration=133, campaign=1, pdays=107, previous=2, poutcome='success', deposit='yes'),
 Row(age=41, job='unknown', marital='single', education='unknown', default='no', balance=942, housing='no', loan='no', contact='cellular', day=27, month='oct', duration=143, campaign=1, pdays=188, previous=1, poutcome='success', deposit='yes'),
 Row(age=41, job='services', marital='married', education='tertiary', default='no', balance=881, housing='no', loan='no', contact='cellular', day=30, month='oct', duration=257, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='unknown', default='no', balance=5372, housing='yes', loan='no', contact='cellular', day=13, month='jan', duration=248, campaign=3, pdays=-1, previous=0, poutcome='unknown', deposit='yes'),
 Row(age=41, job='technician', marital='single', education='tertiary', default='no', balance=1646, housing='yes', loan='no', contact='cellular', day=4, month='feb', duration=261, campaign=1, pdays=184, previous=6, poutcome='success', deposit='yes'),
 Row(age=41, job='management', marital='married', education='tertiary', default='no', balance=27696, housing='no', loan='no', contact='cellular', day=12, month='feb', duration=138, campaign=2, pdays=184, previous=3, poutcome='success', deposit='yes'),
 Row(age=41, job='management', marital='divorced', education='tertiary', default='no', balance=5037, housing='no', loan='no', contact='cellular', day=23, month='apr', duration=252, campaign=9, pdays=185, previous=5, poutcome='other', deposit='yes'),
 Row(age=41, job='unemployed', marital='married', education='tertiary', default='no', balance=0, housing='no', loan='no', contact='cellular', day=29, month='apr', duration=882, campaign=1, pdays=181, previous=3, poutcome='success', deposit='yes'),

In [74]:
row = result[0]
row.asDict()['age']

41

In [75]:
df = spark.read.csv('banking.csv', inferSchema=True, header=True)
df.show(3)

AnalysisException: 'Path does not exist: file:/C:/sparkProjectFolder/banking.csv;'

In [76]:
df.show()

+---+-----------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
|age|        job| marital|education|default|balance|housing|loan|contact|day|month|duration|campaign|pdays|previous|poutcome|deposit|
+---+-----------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
| 59|     admin.| married|secondary|     no|   2343|    yes|  no|unknown|  5|  may|    1042|       1|   -1|       0| unknown|    yes|
| 56|     admin.| married|secondary|     no|     45|     no|  no|unknown|  5|  may|    1467|       1|   -1|       0| unknown|    yes|
| 41| technician| married|secondary|     no|   1270|    yes|  no|unknown|  5|  may|    1389|       1|   -1|       0| unknown|    yes|
| 55|   services| married|secondary|     no|   2476|    yes|  no|unknown|  5|  may|     579|       1|   -1|       0| unknown|    yes|
| 54|     admin.| married| tertiary|     no|    184|     no|  no|unknown|  5|  may|     673|       2|   -1|       0| unknown|    yes|
| 42| management|  single| tertiary|     no|      0|    yes| yes|unknown|  5|  may|     562|       2|   -1|       0| unknown|    yes|
| 56| management| married| tertiary|     no|    830|    yes| yes|unknown|  6|  may|    1201|       1|   -1|       0| unknown|    yes|
| 60|    retired|divorced|secondary|     no|    545|    yes|  no|unknown|  6|  may|    1030|       1|   -1|       0| unknown|    yes|
| 37| technician| married|secondary|     no|      1|    yes|  no|unknown|  6|  may|     608|       1|   -1|       0| unknown|    yes|
| 28|   services|  single|secondary|     no|   5090|    yes|  no|unknown|  6|  may|    1297|       3|   -1|       0| unknown|    yes|
| 38|     admin.|  single|secondary|     no|    100|    yes|  no|unknown|  7|  may|     786|       1|   -1|       0| unknown|    yes|
| 30|blue-collar| married|secondary|     no|    309|    yes|  no|unknown|  7|  may|    1574|       2|   -1|       0| unknown|    yes|
| 29| management| married| tertiary|     no|    199|    yes| yes|unknown|  7|  may|    1689|       4|   -1|       0| unknown|    yes|
| 46|blue-collar|  single| tertiary|     no|    460|    yes|  no|unknown|  7|  may|    1102|       2|   -1|       0| unknown|    yes|
| 31| technician|  single| tertiary|     no|    703|    yes|  no|unknown|  8|  may|     943|       2|   -1|       0| unknown|    yes|
| 35| management|divorced| tertiary|     no|   3837|    yes|  no|unknown|  8|  may|    1084|       1|   -1|       0| unknown|    yes|
| 32|blue-collar|  single|  primary|     no|    611|    yes|  no|unknown|  8|  may|     541|       3|   -1|       0| unknown|    yes|
| 49|   services| married|secondary|     no|     -8|    yes|  no|unknown|  8|  may|    1119|       1|   -1|       0| unknown|    yes|
| 41|     admin.| married|secondary|     no|     55|    yes|  no|unknown|  8|  may|    1120|       2|   -1|       0| unknown|    yes|
| 49|     admin.|divorced|secondary|     no|    168|    yes| yes|unknown|  8|  may|     513|       1|   -1|       0| unknown|    yes|
+---+-----------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
only showing top 20 rows

In [77]:
df.orderBy('education').show()

+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
|age|         job| marital|education|default|balance|housing|loan|contact|day|month|duration|campaign|pdays|previous|poutcome|deposit|
+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
| 41| blue-collar|  single|  primary|     no|   1618|    yes|  no|unknown| 14|  may|    1553|       1|   -1|       0| unknown|    yes|
| 30|entrepreneur|  single|  primary|     no|      0|    yes| yes|unknown| 27|  may|    1051|       1|   -1|       0| unknown|    yes|
| 60|     retired| married|  primary|     no|   1542|    yes|  no|unknown| 14|  may|     930|       1|   -1|       0| unknown|    yes|
| 48| blue-collar|divorced|  primary|     no|     24|    yes|  no|unknown| 14|  may|     832|       1|   -1|       0| unknown|    yes|
| 52| blue-collar|divorced|  primary|     no|   -191|    yes|  no|unknown| 15|  may|     755|       1|   -1|       0| unknown|    yes|
| 60|  technician| married|  primary|     no|     65|    yes|  no|unknown|  9|  may|    1028|       2|   -1|       0| unknown|    yes|
| 59| blue-collar| married|  primary|     no|    320|    yes|  no|unknown| 15|  may|     695|       1|   -1|       0| unknown|    yes|
| 35| blue-collar| married|  primary|     no|    414|     no|  no|unknown| 13|  may|     504|       4|   -1|       0| unknown|    yes|
| 49|     unknown| married|  primary|     no|    341|    yes| yes|unknown| 15|  may|     520|       2|   -1|       0| unknown|    yes|
| 60| blue-collar| married|  primary|     no|   1262|    yes| yes|unknown| 13|  may|    1015|       1|   -1|       0| unknown|    yes|
| 40|    services| married|  primary|     no|     -9|    yes|  no|unknown| 15|  may|     920|       2|   -1|       0| unknown|    yes|
| 53|  technician|divorced|  primary|     no|   1443|    yes|  no|unknown| 14|  may|     476|       1|   -1|       0| unknown|    yes|
| 41|      admin.| married|  primary|     no|   -306|    yes|  no|unknown| 15|  may|     500|       1|   -1|       0| unknown|    yes|
| 35| blue-collar| married|  primary|     no|    102|    yes|  no|unknown| 20|  may|    1334|       1|   -1|       0| unknown|    yes|
| 40| blue-collar| married|  primary|     no|    278|    yes|  no|unknown| 23|  may|    1015|       3|   -1|       0| unknown|    yes|
| 36| blue-collar| married|  primary|     no|    408|    yes| yes|unknown| 20|  may|    1063|       2|   -1|       0| unknown|    yes|
| 32| blue-collar|  single|  primary|     no|    611|    yes|  no|unknown|  8|  may|     541|       3|   -1|       0| unknown|    yes|
| 41| blue-collar| married|  primary|     no|   1250|    yes|  no|unknown| 20|  may|    1392|       2|   -1|       0| unknown|    yes|
| 23|entrepreneur|  single|  primary|     no|      4|    yes|  no|unknown| 13|  may|     395|       2|   -1|       0| unknown|    yes|
| 31| blue-collar|  single|  primary|     no|    216|    yes|  no|unknown| 21|  may|     565|       1|   -1|       0| unknown|    yes|
+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
only showing top 20 rows

In [78]:
df.na.fill(0).show()

+---+-----------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
|age|        job| marital|education|default|balance|housing|loan|contact|day|month|duration|campaign|pdays|previous|poutcome|deposit|
+---+-----------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
| 59|     admin.| married|secondary|     no|   2343|    yes|  no|unknown|  5|  may|    1042|       1|   -1|       0| unknown|    yes|
| 56|     admin.| married|secondary|     no|     45|     no|  no|unknown|  5|  may|    1467|       1|   -1|       0| unknown|    yes|
| 41| technician| married|secondary|     no|   1270|    yes|  no|unknown|  5|  may|    1389|       1|   -1|       0| unknown|    yes|
| 55|   services| married|secondary|     no|   2476|    yes|  no|unknown|  5|  may|     579|       1|   -1|       0| unknown|    yes|
| 54|     admin.| married| tertiary|     no|    184|     no|  no|unknown|  5|  may|     673|       2|   -1|       0| unknown|    yes|
| 42| management|  single| tertiary|     no|      0|    yes| yes|unknown|  5|  may|     562|       2|   -1|       0| unknown|    yes|
| 56| management| married| tertiary|     no|    830|    yes| yes|unknown|  6|  may|    1201|       1|   -1|       0| unknown|    yes|
| 60|    retired|divorced|secondary|     no|    545|    yes|  no|unknown|  6|  may|    1030|       1|   -1|       0| unknown|    yes|
| 37| technician| married|secondary|     no|      1|    yes|  no|unknown|  6|  may|     608|       1|   -1|       0| unknown|    yes|
| 28|   services|  single|secondary|     no|   5090|    yes|  no|unknown|  6|  may|    1297|       3|   -1|       0| unknown|    yes|
| 38|     admin.|  single|secondary|     no|    100|    yes|  no|unknown|  7|  may|     786|       1|   -1|       0| unknown|    yes|
| 30|blue-collar| married|secondary|     no|    309|    yes|  no|unknown|  7|  may|    1574|       2|   -1|       0| unknown|    yes|
| 29| management| married| tertiary|     no|    199|    yes| yes|unknown|  7|  may|    1689|       4|   -1|       0| unknown|    yes|
| 46|blue-collar|  single| tertiary|     no|    460|    yes|  no|unknown|  7|  may|    1102|       2|   -1|       0| unknown|    yes|
| 31| technician|  single| tertiary|     no|    703|    yes|  no|unknown|  8|  may|     943|       2|   -1|       0| unknown|    yes|
| 35| management|divorced| tertiary|     no|   3837|    yes|  no|unknown|  8|  may|    1084|       1|   -1|       0| unknown|    yes|
| 32|blue-collar|  single|  primary|     no|    611|    yes|  no|unknown|  8|  may|     541|       3|   -1|       0| unknown|    yes|
| 49|   services| married|secondary|     no|     -8|    yes|  no|unknown|  8|  may|    1119|       1|   -1|       0| unknown|    yes|
| 41|     admin.| married|secondary|     no|     55|    yes|  no|unknown|  8|  may|    1120|       2|   -1|       0| unknown|    yes|
| 49|     admin.|divorced|secondary|     no|    168|    yes| yes|unknown|  8|  may|     513|       1|   -1|       0| unknown|    yes|
+---+-----------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+-------+
only showing top 20 rows